import { StyleSheet } from 'react-native';

export const productDetailsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 0,
  },
  backButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontWeight: '600',
    color: '#171717',
  },
  headerSpacer: { width: 40 },
  headerFavoriteButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerFavoriteButtonInner: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  headerFavoriteButtonActive: {
    backgroundColor: '#F43F5E',
  },
  headerFavoriteIcon: { width: 20, height: 20 },
  searchBarContainer: {
    paddingHorizontal: 20,
    paddingTop: 6,
    paddingBottom: 2,
  },
  scrollView: { flex: 1 },
  scrollContent: { paddingBottom: 16 },
  imageContainer: {
    width: '100%',
    marginTop: 8,
  },
  imageGalleryWrapper: {
    width: '100%',
    backgroundColor: '#FAFAFA',
    position: 'relative',
  },
  imageSlide: {
    backgroundColor: '#FAFAFA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  productImage: {
    width: '100%',
    height: '100%',
  },
  paginationDots: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
  },
  paginationDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#D1D5DB',
    marginHorizontal: 3,
  },
  paginationDotActive: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#111827',
    marginHorizontal: 2,
  },
  productInfo: {
    paddingHorizontal: 20,
    marginTop: 12,
  },
  categoryText: {
    color: '#6B7280',
    fontWeight: '400',
    marginBottom: 2,
  },
  productName: {
    fontWeight: '600',
    color: '#111827',
    marginBottom: 6,
  },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  ratingLeft: { flexDirection: 'row', alignItems: 'center' },
  ratingText: {
    color: '#111827',
    fontWeight: '400',
    marginLeft: 6,
  },
  description: {
    color: '#6B7280',
    fontWeight: '400',
    marginBottom: 14,
  },
  sectionTitle: {
    fontWeight: '600',
    color: '#111827',
    marginBottom: 10,
  },
  optionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sizeText: {
    fontWeight: '500',
    color: '#111827',
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 12,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#F3F4F6',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 5,
  },
  priceSection: { flex: 1 },
  priceLabel: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '400',
    marginBottom: 2,
  },
  priceValue: {
    fontWeight: '700',
    color: '#111827',
  },
  addToCartButton: { flex: 1, marginLeft: 16 },
  addToCartInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F43F5E',
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 12,
  },
  addToCartText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 8,
  },
});
